Repository Jijuleta/MegaDominator, pull requests merged in 2023-04, with the labels that each got.

#36 2.9.4
  main.py
  requirements.txt
  update.py
Labels: enhancement

#37 bug fix
  main.py
Labels: enhancement

#38 2.9.4
  main.py
Labels: enhancement

#39 2.9.5
  main.py
Labels: enhancement

#41 v2.9.6
  README.md
  main.py
Labels: bug, enhancement

#42 Fixed $play bug
  main.py
Labels: bug, enhancement, invalid

#44 Minor $queue changes and $play fix
  main.py
Labels: enhancement

#45 v2.9.8
  main.py
Labels: bug, enhancement

#46 2.9.9
  main.py
Labels: bug

#47 2.9.9-R2
  main.py
Labels: bug, enhancement

#49 2.9.9 r3
  README.md
  main.py
Labels: bug, enhancement

#50 2.9.9 r3
  main.py
Labels: bug

#51 2.9.9-R3
  main.py
Labels: bug

#52 v2.9.9-R4
  main.py
Labels: bug, enhancement
